### ISSUE TITLE
QgsProcessingException: Error: Algorithm quickosm:buildqueryextent not found

### ISSUE THREAD

**Issue by Yusin2Chen** [xatellite/OpenHousePopulator#1]
Hi, Thank you for your nice code. But I met this problem. Maybe it's the environmental problem.
Could you tell me how to install them rightly? Many thanks~

**Comment by TheNewCivilian** [comment]
Hey @cyx669521! I just added some basic installation instructions. I hope that already helps you getting the script running. In any case let me know if that setup works for you (:

**Comment by TheNewCivilian** [comment]
This week there will also be some updates of the heuristic. So building height and other tags will be considered. I will add some documentation of how the heuristic works to the README later on too.

**Comment by Yusin2Chen** [comment]
Thank you very much~
